"""The fractional-sum GKR prover of V1 on the GPU (Triton): ``V1_SPEC.md`` Sec. 5.4.

Generated by ``gen_gkr_triton.py`` (the product in ``F_{p^8}`` is unrolled); same transcript as
:func:`logup_gkr.prove`, byte for byte (``tests/test_gkr_triton.py``, on a CUDA host).

**Arithmetic.** BabyBear in Montgomery form on uint32 (``R = 2^32``): ``mm(a, b) = a b R^-1 mod p`` by
``lo = a b``, ``hi = umulhi(a, b)``, ``q = lo p^-1 mod 2^32``, ``t = hi - umulhi(q, p)`` (``+ p`` if negative); sums by
an add and a conditional subtraction.  An element of ``F = F_p[x]/(x^8 - 11)`` is 8 planes; arrays are
structure-of-arrays ``[8, n]`` int32 tensors (the bits of the uint32 values).  The verifier-facing values (the top,
the round polynomials, the child values) are converted to canonical form on the host.

**Algorithm** (the eager prover's transcript): the leaves of an instance are built on the device from the residues
and widths (``prove_leaves``) or uploaded (``prove``); the tree is combined layer by layer; for each layer ``k`` the
child arrays are split into their even and odd halves.  Round ``j`` writes ``g_j(t) = s_j eq(rho_j, t) h_j(t)``,
``s_j = prod_{i<j} eq(rho_i, r_i)``, ``h_j(t) = sum_y eq(rho_{>j}, y) F(t, y)`` of degree 2 with
``F = PL QR + QL (PR + lambda QR)``: one kernel (``_round2_kernel``) sums ``h_j(0), h_j(1), h_j(2)`` per block in 64
bits over the suffix eq table (built once per layer, never folded), the host extrapolates ``h_j(3)`` and sends the
eager prover's ``g_j(0), g_j(2), g_j(3)`` (a few products per round on Python ints); then one fold of the four child
arrays at the round's challenge (``_fold4_kernel``).  Per pair and round: 16 products in ``F`` instead of the direct
evaluation's 20, and no claim, inverse or interpolation on the host.
"""

from __future__ import annotations

import os
import sysconfig

import torch

from . import extfield as ef
from .field import P as PRIME

_INCLUDE = os.environ.get("PVI_PY_INCLUDE")
if _INCLUDE:
    _paths = sysconfig.get_paths
    sysconfig.get_paths = lambda *a, **k: {**_paths(*a, **k), "include": _INCLUDE}

try:
    import triton
    import triton.language as tl
except ImportError:                    # pragma: no cover - CPU-only environments
    triton = None

__all__ = ["available", "prove", "prove_leaves"]

R_MOD = (1 << 32) % PRIME
R2 = (1 << 64) % PRIME
R_INV = pow(1 << 32, -1, PRIME)
MU = pow(PRIME, -1, 1 << 32)
B11 = 11 * R_MOD % PRIME
BLOCK = 256


def available(device) -> bool:
    return triton is not None and torch.device(device).type == "cuda"


def _to_mont(v: torch.Tensor) -> list[int]:
    """Canonical ``[8]`` -> 8 Montgomery ints."""
    return [int(c) * R_MOD % PRIME for c in v.tolist()]


def _from_mont(planes: torch.Tensor) -> torch.Tensor:
    """Montgomery values (int64 tensor, any shape, in ``[0, p)``) -> canonical int64."""
    return (planes.to(torch.int64) % PRIME) * R_INV % PRIME


def _consts():
    return dict(P_=PRIME, MU_=MU, B11_=B11)


if triton is not None:
    @triton.jit
    def _mm(a, b, P, MU):
        lo = a * b
        hi = tl.umulhi(a, b)
        q = lo * MU
        u = tl.umulhi(q, P)
        t = hi - u
        return tl.where(hi < u, t + P, t)

    @triton.jit
    def _add(a, b, P):
        s = a + b
        return tl.where(s >= P, s - P, s)

    @triton.jit
    def _sub(a, b, P):
        d = a - b
        return tl.where(a < b, d + P, d)


    @triton.jit
    def _emul(a0, a1, a2, a3, a4, a5, a6, a7, b0, b1, b2, b3, b4, b5, b6, b7, P, MU, B11):
        """``a b`` in ``F_{p^8}`` (Montgomery planes): ``c_k = sum_{i+j=k} a_i b_j + 11 sum_{i+j=k+8} a_i b_j``."""
        c0 = _mm(a0, b0, P, MU)
        c0 = _add(c0, _mm(_add(_add(_add(_add(_add(_add(_mm(a1, b7, P, MU), _mm(a2, b6, P, MU), P), _mm(a3, b5, P, MU), P), _mm(a4, b4, P, MU), P), _mm(a5, b3, P, MU), P), _mm(a6, b2, P, MU), P), _mm(a7, b1, P, MU), P), B11, P, MU), P)
        c1 = _add(_mm(a0, b1, P, MU), _mm(a1, b0, P, MU), P)
        c1 = _add(c1, _mm(_add(_add(_add(_add(_add(_mm(a2, b7, P, MU), _mm(a3, b6, P, MU), P), _mm(a4, b5, P, MU), P), _mm(a5, b4, P, MU), P), _mm(a6, b3, P, MU), P), _mm(a7, b2, P, MU), P), B11, P, MU), P)
        c2 = _add(_add(_mm(a0, b2, P, MU), _mm(a1, b1, P, MU), P), _mm(a2, b0, P, MU), P)
        c2 = _add(c2, _mm(_add(_add(_add(_add(_mm(a3, b7, P, MU), _mm(a4, b6, P, MU), P), _mm(a5, b5, P, MU), P), _mm(a6, b4, P, MU), P), _mm(a7, b3, P, MU), P), B11, P, MU), P)
        c3 = _add(_add(_add(_mm(a0, b3, P, MU), _mm(a1, b2, P, MU), P), _mm(a2, b1, P, MU), P), _mm(a3, b0, P, MU), P)
        c3 = _add(c3, _mm(_add(_add(_add(_mm(a4, b7, P, MU), _mm(a5, b6, P, MU), P), _mm(a6, b5, P, MU), P), _mm(a7, b4, P, MU), P), B11, P, MU), P)
        c4 = _add(_add(_add(_add(_mm(a0, b4, P, MU), _mm(a1, b3, P, MU), P), _mm(a2, b2, P, MU), P), _mm(a3, b1, P, MU), P), _mm(a4, b0, P, MU), P)
        c4 = _add(c4, _mm(_add(_add(_mm(a5, b7, P, MU), _mm(a6, b6, P, MU), P), _mm(a7, b5, P, MU), P), B11, P, MU), P)
        c5 = _add(_add(_add(_add(_add(_mm(a0, b5, P, MU), _mm(a1, b4, P, MU), P), _mm(a2, b3, P, MU), P), _mm(a3, b2, P, MU), P), _mm(a4, b1, P, MU), P), _mm(a5, b0, P, MU), P)
        c5 = _add(c5, _mm(_add(_mm(a6, b7, P, MU), _mm(a7, b6, P, MU), P), B11, P, MU), P)
        c6 = _add(_add(_add(_add(_add(_add(_mm(a0, b6, P, MU), _mm(a1, b5, P, MU), P), _mm(a2, b4, P, MU), P), _mm(a3, b3, P, MU), P), _mm(a4, b2, P, MU), P), _mm(a5, b1, P, MU), P), _mm(a6, b0, P, MU), P)
        c6 = _add(c6, _mm(_mm(a7, b7, P, MU), B11, P, MU), P)
        c7 = _add(_add(_add(_add(_add(_add(_add(_mm(a0, b7, P, MU), _mm(a1, b6, P, MU), P), _mm(a2, b5, P, MU), P), _mm(a3, b4, P, MU), P), _mm(a4, b3, P, MU), P), _mm(a5, b2, P, MU), P), _mm(a6, b1, P, MU), P), _mm(a7, b0, P, MU), P)
        return c0, c1, c2, c3, c4, c5, c6, c7

    @triton.jit(do_not_specialize=['al0', 'al1', 'al2', 'al3', 'al4', 'al5', 'al6', 'al7', 'rows', 'T', 'n_col', 'total', 'stride', 'P_', 'MU_', 'R2_', 'ONE_'])
    def _leaf_kernel(d_ptr, w_ptr, p_ptr, q_ptr, al0, al1, al2, al3, al4, al5, al6, al7, rows, T, n_col, total, stride, P_, MU_, R2_, ONE_,
                     BLOCK: tl.constexpr):
        P = P_.to(tl.uint32)
        MU = MU_.to(tl.uint32)
        R2 = R2_.to(tl.uint32)
        ONE = ONE_.to(tl.uint32)
        i = tl.program_id(0).to(tl.int64) * BLOCK + tl.arange(0, BLOCK)
        inb = i < total
        row = i >> n_col
        col = i & ((1 << n_col) - 1)
        real = (row < rows) & (col < T) & inb
        src = row * T + col
        d = tl.load(d_ptr + src, mask=real, other=0).to(tl.uint32, bitcast=True)
        w = tl.load(w_ptr + src, mask=real, other=0).to(tl.uint32, bitcast=True)
        dm = _mm(d, R2, P, MU)
        wm = _mm(w, R2, P, MU)
        zero = d * 0
        q0 = tl.where(real, _sub(al0.to(tl.uint32), dm, P), ONE + zero)
        q1 = tl.where(real, _sub(al1.to(tl.uint32), wm, P), zero)
        q2 = tl.where(real, al2.to(tl.uint32) + zero, zero)
        q3 = tl.where(real, al3.to(tl.uint32) + zero, zero)
        q4 = tl.where(real, al4.to(tl.uint32) + zero, zero)
        q5 = tl.where(real, al5.to(tl.uint32) + zero, zero)
        q6 = tl.where(real, al6.to(tl.uint32) + zero, zero)
        q7 = tl.where(real, al7.to(tl.uint32) + zero, zero)
        p0 = tl.where(real, ONE + zero, zero)
        tl.store(p_ptr + 0 * stride + i, p0.to(tl.int32, bitcast=True), mask=inb)
        tl.store(p_ptr + 1 * stride + i, zero.to(tl.int32, bitcast=True), mask=inb)
        tl.store(p_ptr + 2 * stride + i, zero.to(tl.int32, bitcast=True), mask=inb)
        tl.store(p_ptr + 3 * stride + i, zero.to(tl.int32, bitcast=True), mask=inb)
        tl.store(p_ptr + 4 * stride + i, zero.to(tl.int32, bitcast=True), mask=inb)
        tl.store(p_ptr + 5 * stride + i, zero.to(tl.int32, bitcast=True), mask=inb)
        tl.store(p_ptr + 6 * stride + i, zero.to(tl.int32, bitcast=True), mask=inb)
        tl.store(p_ptr + 7 * stride + i, zero.to(tl.int32, bitcast=True), mask=inb)
        tl.store(q_ptr + 0 * stride + i, q0.to(tl.int32, bitcast=True), mask=inb)
        tl.store(q_ptr + 1 * stride + i, q1.to(tl.int32, bitcast=True), mask=inb)
        tl.store(q_ptr + 2 * stride + i, q2.to(tl.int32, bitcast=True), mask=inb)
        tl.store(q_ptr + 3 * stride + i, q3.to(tl.int32, bitcast=True), mask=inb)
        tl.store(q_ptr + 4 * stride + i, q4.to(tl.int32, bitcast=True), mask=inb)
        tl.store(q_ptr + 5 * stride + i, q5.to(tl.int32, bitcast=True), mask=inb)
        tl.store(q_ptr + 6 * stride + i, q6.to(tl.int32, bitcast=True), mask=inb)
        tl.store(q_ptr + 7 * stride + i, q7.to(tl.int32, bitcast=True), mask=inb)

    @triton.jit(do_not_specialize=['m_out', 's_in', 's_out', 'P_', 'MU_', 'B11_'])
    def _combine_kernel(pi, qi, po, qo, m_out, s_in, s_out, P_, MU_, B11_, BLOCK: tl.constexpr):
        P = P_.to(tl.uint32)
        MU = MU_.to(tl.uint32)
        B11 = B11_.to(tl.uint32)
        y = tl.program_id(0).to(tl.int64) * BLOCK + tl.arange(0, BLOCK)
        mask = y < m_out
        pl0 = tl.load(pi + 0 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pl1 = tl.load(pi + 1 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pl2 = tl.load(pi + 2 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pl3 = tl.load(pi + 3 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pl4 = tl.load(pi + 4 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pl5 = tl.load(pi + 5 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pl6 = tl.load(pi + 6 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pl7 = tl.load(pi + 7 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pr0 = tl.load(pi + 0 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pr1 = tl.load(pi + 1 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pr2 = tl.load(pi + 2 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pr3 = tl.load(pi + 3 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pr4 = tl.load(pi + 4 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pr5 = tl.load(pi + 5 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pr6 = tl.load(pi + 6 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pr7 = tl.load(pi + 7 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        ql0 = tl.load(qi + 0 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        ql1 = tl.load(qi + 1 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        ql2 = tl.load(qi + 2 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        ql3 = tl.load(qi + 3 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        ql4 = tl.load(qi + 4 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        ql5 = tl.load(qi + 5 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        ql6 = tl.load(qi + 6 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        ql7 = tl.load(qi + 7 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qr0 = tl.load(qi + 0 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qr1 = tl.load(qi + 1 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qr2 = tl.load(qi + 2 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qr3 = tl.load(qi + 3 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qr4 = tl.load(qi + 4 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qr5 = tl.load(qi + 5 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qr6 = tl.load(qi + 6 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qr7 = tl.load(qi + 7 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        u0, u1, u2, u3, u4, u5, u6, u7 = _emul(pl0, pl1, pl2, pl3, pl4, pl5, pl6, pl7, qr0, qr1, qr2, qr3, qr4, qr5, qr6, qr7, P, MU, B11)
        v0, v1, v2, v3, v4, v5, v6, v7 = _emul(pr0, pr1, pr2, pr3, pr4, pr5, pr6, pr7, ql0, ql1, ql2, ql3, ql4, ql5, ql6, ql7, P, MU, B11)
        np0 = _add(u0, v0, P)
        np1 = _add(u1, v1, P)
        np2 = _add(u2, v2, P)
        np3 = _add(u3, v3, P)
        np4 = _add(u4, v4, P)
        np5 = _add(u5, v5, P)
        np6 = _add(u6, v6, P)
        np7 = _add(u7, v7, P)
        nq0, nq1, nq2, nq3, nq4, nq5, nq6, nq7 = _emul(ql0, ql1, ql2, ql3, ql4, ql5, ql6, ql7, qr0, qr1, qr2, qr3, qr4, qr5, qr6, qr7, P, MU, B11)
        tl.store(po + 0 * s_out + y, np0.to(tl.int32, bitcast=True), mask=mask)
        tl.store(po + 1 * s_out + y, np1.to(tl.int32, bitcast=True), mask=mask)
        tl.store(po + 2 * s_out + y, np2.to(tl.int32, bitcast=True), mask=mask)
        tl.store(po + 3 * s_out + y, np3.to(tl.int32, bitcast=True), mask=mask)
        tl.store(po + 4 * s_out + y, np4.to(tl.int32, bitcast=True), mask=mask)
        tl.store(po + 5 * s_out + y, np5.to(tl.int32, bitcast=True), mask=mask)
        tl.store(po + 6 * s_out + y, np6.to(tl.int32, bitcast=True), mask=mask)
        tl.store(po + 7 * s_out + y, np7.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qo + 0 * s_out + y, nq0.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qo + 1 * s_out + y, nq1.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qo + 2 * s_out + y, nq2.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qo + 3 * s_out + y, nq3.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qo + 4 * s_out + y, nq4.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qo + 5 * s_out + y, nq5.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qo + 6 * s_out + y, nq6.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qo + 7 * s_out + y, nq7.to(tl.int32, bitcast=True), mask=mask)

    @triton.jit(do_not_specialize=['r0', 'r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 's0', 's1', 's2', 's3', 's4', 's5', 's6', 's7', 'm', 's_in', 's_out', 'inter', 'P_', 'MU_', 'B11_'])
    def _eq_kernel(ti, to, r0, r1, r2, r3, r4, r5, r6, r7, s0, s1, s2, s3, s4, s5, s6, s7, m, s_in, s_out, inter, P_, MU_, B11_, BLOCK: tl.constexpr):
        P = P_.to(tl.uint32)
        MU = MU_.to(tl.uint32)
        B11 = B11_.to(tl.uint32)
        y = tl.program_id(0).to(tl.int64) * BLOCK + tl.arange(0, BLOCK)
        mask = y < m
        t0 = tl.load(ti + 0 * s_in + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        t1 = tl.load(ti + 1 * s_in + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        t2 = tl.load(ti + 2 * s_in + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        t3 = tl.load(ti + 3 * s_in + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        t4 = tl.load(ti + 4 * s_in + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        t5 = tl.load(ti + 5 * s_in + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        t6 = tl.load(ti + 6 * s_in + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        t7 = tl.load(ti + 7 * s_in + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        rr0 = r0.to(tl.uint32) + t0 * 0
        rr1 = r1.to(tl.uint32) + t0 * 0
        rr2 = r2.to(tl.uint32) + t0 * 0
        rr3 = r3.to(tl.uint32) + t0 * 0
        rr4 = r4.to(tl.uint32) + t0 * 0
        rr5 = r5.to(tl.uint32) + t0 * 0
        rr6 = r6.to(tl.uint32) + t0 * 0
        rr7 = r7.to(tl.uint32) + t0 * 0
        ss0 = s0.to(tl.uint32) + t0 * 0
        ss1 = s1.to(tl.uint32) + t0 * 0
        ss2 = s2.to(tl.uint32) + t0 * 0
        ss3 = s3.to(tl.uint32) + t0 * 0
        ss4 = s4.to(tl.uint32) + t0 * 0
        ss5 = s5.to(tl.uint32) + t0 * 0
        ss6 = s6.to(tl.uint32) + t0 * 0
        ss7 = s7.to(tl.uint32) + t0 * 0
        lo0, lo1, lo2, lo3, lo4, lo5, lo6, lo7 = _emul(t0, t1, t2, t3, t4, t5, t6, t7, ss0, ss1, ss2, ss3, ss4, ss5, ss6, ss7, P, MU, B11)
        hi0, hi1, hi2, hi3, hi4, hi5, hi6, hi7 = _emul(t0, t1, t2, t3, t4, t5, t6, t7, rr0, rr1, rr2, rr3, rr4, rr5, rr6, rr7, P, MU, B11)
        lo_at = tl.where(inter == 1, 2 * y, y)
        hi_at = tl.where(inter == 1, 2 * y + 1, y + m)
        tl.store(to + 0 * s_out + lo_at, lo0.to(tl.int32, bitcast=True), mask=mask)
        tl.store(to + 1 * s_out + lo_at, lo1.to(tl.int32, bitcast=True), mask=mask)
        tl.store(to + 2 * s_out + lo_at, lo2.to(tl.int32, bitcast=True), mask=mask)
        tl.store(to + 3 * s_out + lo_at, lo3.to(tl.int32, bitcast=True), mask=mask)
        tl.store(to + 4 * s_out + lo_at, lo4.to(tl.int32, bitcast=True), mask=mask)
        tl.store(to + 5 * s_out + lo_at, lo5.to(tl.int32, bitcast=True), mask=mask)
        tl.store(to + 6 * s_out + lo_at, lo6.to(tl.int32, bitcast=True), mask=mask)
        tl.store(to + 7 * s_out + lo_at, lo7.to(tl.int32, bitcast=True), mask=mask)
        tl.store(to + 0 * s_out + hi_at, hi0.to(tl.int32, bitcast=True), mask=mask)
        tl.store(to + 1 * s_out + hi_at, hi1.to(tl.int32, bitcast=True), mask=mask)
        tl.store(to + 2 * s_out + hi_at, hi2.to(tl.int32, bitcast=True), mask=mask)
        tl.store(to + 3 * s_out + hi_at, hi3.to(tl.int32, bitcast=True), mask=mask)
        tl.store(to + 4 * s_out + hi_at, hi4.to(tl.int32, bitcast=True), mask=mask)
        tl.store(to + 5 * s_out + hi_at, hi5.to(tl.int32, bitcast=True), mask=mask)
        tl.store(to + 6 * s_out + hi_at, hi6.to(tl.int32, bitcast=True), mask=mask)
        tl.store(to + 7 * s_out + hi_at, hi7.to(tl.int32, bitcast=True), mask=mask)

    @triton.jit(do_not_specialize=['lam0', 'lam1', 'lam2', 'lam3', 'lam4', 'lam5', 'lam6', 'lam7', 'half', 's', 'P_', 'MU_', 'B11_'])
    def _round2_kernel(e, pl, pr, ql, qr, out, lam0, lam1, lam2, lam3, lam4, lam5, lam6, lam7, half, s, P_, MU_, B11_, BLOCK: tl.constexpr):
        P = P_.to(tl.uint32)
        MU = MU_.to(tl.uint32)
        B11 = B11_.to(tl.uint32)
        pid = tl.program_id(0)
        y = pid.to(tl.int64) * BLOCK + tl.arange(0, BLOCK)
        mask = y < half
        et0 = tl.load(e + 0 * half + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        et1 = tl.load(e + 1 * half + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        et2 = tl.load(e + 2 * half + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        et3 = tl.load(e + 3 * half + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        et4 = tl.load(e + 4 * half + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        et5 = tl.load(e + 5 * half + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        et6 = tl.load(e + 6 * half + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        et7 = tl.load(e + 7 * half + y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pla0 = tl.load(pl + 0 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pla1 = tl.load(pl + 1 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pla2 = tl.load(pl + 2 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pla3 = tl.load(pl + 3 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pla4 = tl.load(pl + 4 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pla5 = tl.load(pl + 5 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pla6 = tl.load(pl + 6 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pla7 = tl.load(pl + 7 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb0 = tl.load(pl + 0 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb1 = tl.load(pl + 1 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb2 = tl.load(pl + 2 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb3 = tl.load(pl + 3 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb4 = tl.load(pl + 4 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb5 = tl.load(pl + 5 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb6 = tl.load(pl + 6 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb7 = tl.load(pl + 7 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pld0 = _sub(plb0, pla0, P)
        pld1 = _sub(plb1, pla1, P)
        pld2 = _sub(plb2, pla2, P)
        pld3 = _sub(plb3, pla3, P)
        pld4 = _sub(plb4, pla4, P)
        pld5 = _sub(plb5, pla5, P)
        pld6 = _sub(plb6, pla6, P)
        pld7 = _sub(plb7, pla7, P)
        pra0 = tl.load(pr + 0 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pra1 = tl.load(pr + 1 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pra2 = tl.load(pr + 2 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pra3 = tl.load(pr + 3 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pra4 = tl.load(pr + 4 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pra5 = tl.load(pr + 5 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pra6 = tl.load(pr + 6 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pra7 = tl.load(pr + 7 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb0 = tl.load(pr + 0 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb1 = tl.load(pr + 1 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb2 = tl.load(pr + 2 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb3 = tl.load(pr + 3 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb4 = tl.load(pr + 4 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb5 = tl.load(pr + 5 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb6 = tl.load(pr + 6 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb7 = tl.load(pr + 7 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prd0 = _sub(prb0, pra0, P)
        prd1 = _sub(prb1, pra1, P)
        prd2 = _sub(prb2, pra2, P)
        prd3 = _sub(prb3, pra3, P)
        prd4 = _sub(prb4, pra4, P)
        prd5 = _sub(prb5, pra5, P)
        prd6 = _sub(prb6, pra6, P)
        prd7 = _sub(prb7, pra7, P)
        qla0 = tl.load(ql + 0 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qla1 = tl.load(ql + 1 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qla2 = tl.load(ql + 2 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qla3 = tl.load(ql + 3 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qla4 = tl.load(ql + 4 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qla5 = tl.load(ql + 5 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qla6 = tl.load(ql + 6 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qla7 = tl.load(ql + 7 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb0 = tl.load(ql + 0 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb1 = tl.load(ql + 1 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb2 = tl.load(ql + 2 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb3 = tl.load(ql + 3 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb4 = tl.load(ql + 4 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb5 = tl.load(ql + 5 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb6 = tl.load(ql + 6 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb7 = tl.load(ql + 7 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qld0 = _sub(qlb0, qla0, P)
        qld1 = _sub(qlb1, qla1, P)
        qld2 = _sub(qlb2, qla2, P)
        qld3 = _sub(qlb3, qla3, P)
        qld4 = _sub(qlb4, qla4, P)
        qld5 = _sub(qlb5, qla5, P)
        qld6 = _sub(qlb6, qla6, P)
        qld7 = _sub(qlb7, qla7, P)
        qra0 = tl.load(qr + 0 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qra1 = tl.load(qr + 1 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qra2 = tl.load(qr + 2 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qra3 = tl.load(qr + 3 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qra4 = tl.load(qr + 4 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qra5 = tl.load(qr + 5 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qra6 = tl.load(qr + 6 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qra7 = tl.load(qr + 7 * s + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb0 = tl.load(qr + 0 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb1 = tl.load(qr + 1 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb2 = tl.load(qr + 2 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb3 = tl.load(qr + 3 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb4 = tl.load(qr + 4 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb5 = tl.load(qr + 5 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb6 = tl.load(qr + 6 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb7 = tl.load(qr + 7 * s + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrd0 = _sub(qrb0, qra0, P)
        qrd1 = _sub(qrb1, qra1, P)
        qrd2 = _sub(qrb2, qra2, P)
        qrd3 = _sub(qrb3, qra3, P)
        qrd4 = _sub(qrb4, qra4, P)
        qrd5 = _sub(qrb5, qra5, P)
        qrd6 = _sub(qrb6, qra6, P)
        qrd7 = _sub(qrb7, qra7, P)
        lm0 = lam0.to(tl.uint32) + et0 * 0
        lm1 = lam1.to(tl.uint32) + et0 * 0
        lm2 = lam2.to(tl.uint32) + et0 * 0
        lm3 = lam3.to(tl.uint32) + et0 * 0
        lm4 = lam4.to(tl.uint32) + et0 * 0
        lm5 = lam5.to(tl.uint32) + et0 * 0
        lm6 = lam6.to(tl.uint32) + et0 * 0
        lm7 = lam7.to(tl.uint32) + et0 * 0
        plt0 = pla0
        plt1 = pla1
        plt2 = pla2
        plt3 = pla3
        plt4 = pla4
        plt5 = pla5
        plt6 = pla6
        plt7 = pla7
        prt0 = pra0
        prt1 = pra1
        prt2 = pra2
        prt3 = pra3
        prt4 = pra4
        prt5 = pra5
        prt6 = pra6
        prt7 = pra7
        qlt0 = qla0
        qlt1 = qla1
        qlt2 = qla2
        qlt3 = qla3
        qlt4 = qla4
        qlt5 = qla5
        qlt6 = qla6
        qlt7 = qla7
        qrt0 = qra0
        qrt1 = qra1
        qrt2 = qra2
        qrt3 = qra3
        qrt4 = qra4
        qrt5 = qra5
        qrt6 = qra6
        qrt7 = qra7
        u_0, u_1, u_2, u_3, u_4, u_5, u_6, u_7 = _emul(lm0, lm1, lm2, lm3, lm4, lm5, lm6, lm7, qrt0, qrt1, qrt2, qrt3, qrt4, qrt5, qrt6, qrt7, P, MU, B11)
        v_0 = _add(prt0, u_0, P)
        v_1 = _add(prt1, u_1, P)
        v_2 = _add(prt2, u_2, P)
        v_3 = _add(prt3, u_3, P)
        v_4 = _add(prt4, u_4, P)
        v_5 = _add(prt5, u_5, P)
        v_6 = _add(prt6, u_6, P)
        v_7 = _add(prt7, u_7, P)
        f1_0, f1_1, f1_2, f1_3, f1_4, f1_5, f1_6, f1_7 = _emul(plt0, plt1, plt2, plt3, plt4, plt5, plt6, plt7, qrt0, qrt1, qrt2, qrt3, qrt4, qrt5, qrt6, qrt7, P, MU, B11)
        f2_0, f2_1, f2_2, f2_3, f2_4, f2_5, f2_6, f2_7 = _emul(qlt0, qlt1, qlt2, qlt3, qlt4, qlt5, qlt6, qlt7, v_0, v_1, v_2, v_3, v_4, v_5, v_6, v_7, P, MU, B11)
        ff0 = _add(f1_0, f2_0, P)
        ff1 = _add(f1_1, f2_1, P)
        ff2 = _add(f1_2, f2_2, P)
        ff3 = _add(f1_3, f2_3, P)
        ff4 = _add(f1_4, f2_4, P)
        ff5 = _add(f1_5, f2_5, P)
        ff6 = _add(f1_6, f2_6, P)
        ff7 = _add(f1_7, f2_7, P)
        g_0, g_1, g_2, g_3, g_4, g_5, g_6, g_7 = _emul(et0, et1, et2, et3, et4, et5, et6, et7, ff0, ff1, ff2, ff3, ff4, ff5, ff6, ff7, P, MU, B11)
        tl.store(out + (pid * 3 + 0) * 8 + 0, tl.sum(tl.where(mask, g_0, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 0) * 8 + 1, tl.sum(tl.where(mask, g_1, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 0) * 8 + 2, tl.sum(tl.where(mask, g_2, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 0) * 8 + 3, tl.sum(tl.where(mask, g_3, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 0) * 8 + 4, tl.sum(tl.where(mask, g_4, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 0) * 8 + 5, tl.sum(tl.where(mask, g_5, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 0) * 8 + 6, tl.sum(tl.where(mask, g_6, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 0) * 8 + 7, tl.sum(tl.where(mask, g_7, 0).to(tl.uint64), axis=0).to(tl.int64))
        plt0 = plb0
        plt1 = plb1
        plt2 = plb2
        plt3 = plb3
        plt4 = plb4
        plt5 = plb5
        plt6 = plb6
        plt7 = plb7
        prt0 = prb0
        prt1 = prb1
        prt2 = prb2
        prt3 = prb3
        prt4 = prb4
        prt5 = prb5
        prt6 = prb6
        prt7 = prb7
        qlt0 = qlb0
        qlt1 = qlb1
        qlt2 = qlb2
        qlt3 = qlb3
        qlt4 = qlb4
        qlt5 = qlb5
        qlt6 = qlb6
        qlt7 = qlb7
        qrt0 = qrb0
        qrt1 = qrb1
        qrt2 = qrb2
        qrt3 = qrb3
        qrt4 = qrb4
        qrt5 = qrb5
        qrt6 = qrb6
        qrt7 = qrb7
        u_0, u_1, u_2, u_3, u_4, u_5, u_6, u_7 = _emul(lm0, lm1, lm2, lm3, lm4, lm5, lm6, lm7, qrt0, qrt1, qrt2, qrt3, qrt4, qrt5, qrt6, qrt7, P, MU, B11)
        v_0 = _add(prt0, u_0, P)
        v_1 = _add(prt1, u_1, P)
        v_2 = _add(prt2, u_2, P)
        v_3 = _add(prt3, u_3, P)
        v_4 = _add(prt4, u_4, P)
        v_5 = _add(prt5, u_5, P)
        v_6 = _add(prt6, u_6, P)
        v_7 = _add(prt7, u_7, P)
        f1_0, f1_1, f1_2, f1_3, f1_4, f1_5, f1_6, f1_7 = _emul(plt0, plt1, plt2, plt3, plt4, plt5, plt6, plt7, qrt0, qrt1, qrt2, qrt3, qrt4, qrt5, qrt6, qrt7, P, MU, B11)
        f2_0, f2_1, f2_2, f2_3, f2_4, f2_5, f2_6, f2_7 = _emul(qlt0, qlt1, qlt2, qlt3, qlt4, qlt5, qlt6, qlt7, v_0, v_1, v_2, v_3, v_4, v_5, v_6, v_7, P, MU, B11)
        ff0 = _add(f1_0, f2_0, P)
        ff1 = _add(f1_1, f2_1, P)
        ff2 = _add(f1_2, f2_2, P)
        ff3 = _add(f1_3, f2_3, P)
        ff4 = _add(f1_4, f2_4, P)
        ff5 = _add(f1_5, f2_5, P)
        ff6 = _add(f1_6, f2_6, P)
        ff7 = _add(f1_7, f2_7, P)
        g_0, g_1, g_2, g_3, g_4, g_5, g_6, g_7 = _emul(et0, et1, et2, et3, et4, et5, et6, et7, ff0, ff1, ff2, ff3, ff4, ff5, ff6, ff7, P, MU, B11)
        tl.store(out + (pid * 3 + 1) * 8 + 0, tl.sum(tl.where(mask, g_0, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 1) * 8 + 1, tl.sum(tl.where(mask, g_1, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 1) * 8 + 2, tl.sum(tl.where(mask, g_2, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 1) * 8 + 3, tl.sum(tl.where(mask, g_3, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 1) * 8 + 4, tl.sum(tl.where(mask, g_4, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 1) * 8 + 5, tl.sum(tl.where(mask, g_5, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 1) * 8 + 6, tl.sum(tl.where(mask, g_6, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 1) * 8 + 7, tl.sum(tl.where(mask, g_7, 0).to(tl.uint64), axis=0).to(tl.int64))
        plt0 = _add(plb0, pld0, P)
        plt1 = _add(plb1, pld1, P)
        plt2 = _add(plb2, pld2, P)
        plt3 = _add(plb3, pld3, P)
        plt4 = _add(plb4, pld4, P)
        plt5 = _add(plb5, pld5, P)
        plt6 = _add(plb6, pld6, P)
        plt7 = _add(plb7, pld7, P)
        prt0 = _add(prb0, prd0, P)
        prt1 = _add(prb1, prd1, P)
        prt2 = _add(prb2, prd2, P)
        prt3 = _add(prb3, prd3, P)
        prt4 = _add(prb4, prd4, P)
        prt5 = _add(prb5, prd5, P)
        prt6 = _add(prb6, prd6, P)
        prt7 = _add(prb7, prd7, P)
        qlt0 = _add(qlb0, qld0, P)
        qlt1 = _add(qlb1, qld1, P)
        qlt2 = _add(qlb2, qld2, P)
        qlt3 = _add(qlb3, qld3, P)
        qlt4 = _add(qlb4, qld4, P)
        qlt5 = _add(qlb5, qld5, P)
        qlt6 = _add(qlb6, qld6, P)
        qlt7 = _add(qlb7, qld7, P)
        qrt0 = _add(qrb0, qrd0, P)
        qrt1 = _add(qrb1, qrd1, P)
        qrt2 = _add(qrb2, qrd2, P)
        qrt3 = _add(qrb3, qrd3, P)
        qrt4 = _add(qrb4, qrd4, P)
        qrt5 = _add(qrb5, qrd5, P)
        qrt6 = _add(qrb6, qrd6, P)
        qrt7 = _add(qrb7, qrd7, P)
        u_0, u_1, u_2, u_3, u_4, u_5, u_6, u_7 = _emul(lm0, lm1, lm2, lm3, lm4, lm5, lm6, lm7, qrt0, qrt1, qrt2, qrt3, qrt4, qrt5, qrt6, qrt7, P, MU, B11)
        v_0 = _add(prt0, u_0, P)
        v_1 = _add(prt1, u_1, P)
        v_2 = _add(prt2, u_2, P)
        v_3 = _add(prt3, u_3, P)
        v_4 = _add(prt4, u_4, P)
        v_5 = _add(prt5, u_5, P)
        v_6 = _add(prt6, u_6, P)
        v_7 = _add(prt7, u_7, P)
        f1_0, f1_1, f1_2, f1_3, f1_4, f1_5, f1_6, f1_7 = _emul(plt0, plt1, plt2, plt3, plt4, plt5, plt6, plt7, qrt0, qrt1, qrt2, qrt3, qrt4, qrt5, qrt6, qrt7, P, MU, B11)
        f2_0, f2_1, f2_2, f2_3, f2_4, f2_5, f2_6, f2_7 = _emul(qlt0, qlt1, qlt2, qlt3, qlt4, qlt5, qlt6, qlt7, v_0, v_1, v_2, v_3, v_4, v_5, v_6, v_7, P, MU, B11)
        ff0 = _add(f1_0, f2_0, P)
        ff1 = _add(f1_1, f2_1, P)
        ff2 = _add(f1_2, f2_2, P)
        ff3 = _add(f1_3, f2_3, P)
        ff4 = _add(f1_4, f2_4, P)
        ff5 = _add(f1_5, f2_5, P)
        ff6 = _add(f1_6, f2_6, P)
        ff7 = _add(f1_7, f2_7, P)
        g_0, g_1, g_2, g_3, g_4, g_5, g_6, g_7 = _emul(et0, et1, et2, et3, et4, et5, et6, et7, ff0, ff1, ff2, ff3, ff4, ff5, ff6, ff7, P, MU, B11)
        tl.store(out + (pid * 3 + 2) * 8 + 0, tl.sum(tl.where(mask, g_0, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 2) * 8 + 1, tl.sum(tl.where(mask, g_1, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 2) * 8 + 2, tl.sum(tl.where(mask, g_2, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 2) * 8 + 3, tl.sum(tl.where(mask, g_3, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 2) * 8 + 4, tl.sum(tl.where(mask, g_4, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 2) * 8 + 5, tl.sum(tl.where(mask, g_5, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 2) * 8 + 6, tl.sum(tl.where(mask, g_6, 0).to(tl.uint64), axis=0).to(tl.int64))
        tl.store(out + (pid * 3 + 2) * 8 + 7, tl.sum(tl.where(mask, g_7, 0).to(tl.uint64), axis=0).to(tl.int64))

    @triton.jit(do_not_specialize=['r0', 'r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'half', 's_in', 's_out', 'P_', 'MU_', 'B11_'])
    def _fold4_kernel(pl, pr, ql, qr, plo, pro, qlo, qro, r0, r1, r2, r3, r4, r5, r6, r7, half, s_in, s_out, P_, MU_, B11_,
                      BLOCK: tl.constexpr):
        P = P_.to(tl.uint32)
        MU = MU_.to(tl.uint32)
        B11 = B11_.to(tl.uint32)
        y = tl.program_id(0).to(tl.int64) * BLOCK + tl.arange(0, BLOCK)
        mask = y < half
        pla0 = tl.load(pl + 0 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pla1 = tl.load(pl + 1 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pla2 = tl.load(pl + 2 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pla3 = tl.load(pl + 3 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pla4 = tl.load(pl + 4 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pla5 = tl.load(pl + 5 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pla6 = tl.load(pl + 6 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pla7 = tl.load(pl + 7 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb0 = tl.load(pl + 0 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb1 = tl.load(pl + 1 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb2 = tl.load(pl + 2 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb3 = tl.load(pl + 3 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb4 = tl.load(pl + 4 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb5 = tl.load(pl + 5 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb6 = tl.load(pl + 6 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        plb7 = tl.load(pl + 7 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        rr0 = r0.to(tl.uint32) + pla0 * 0
        rr1 = r1.to(tl.uint32) + pla0 * 0
        rr2 = r2.to(tl.uint32) + pla0 * 0
        rr3 = r3.to(tl.uint32) + pla0 * 0
        rr4 = r4.to(tl.uint32) + pla0 * 0
        rr5 = r5.to(tl.uint32) + pla0 * 0
        rr6 = r6.to(tl.uint32) + pla0 * 0
        rr7 = r7.to(tl.uint32) + pla0 * 0
        pld0 = _sub(plb0, pla0, P)
        pld1 = _sub(plb1, pla1, P)
        pld2 = _sub(plb2, pla2, P)
        pld3 = _sub(plb3, pla3, P)
        pld4 = _sub(plb4, pla4, P)
        pld5 = _sub(plb5, pla5, P)
        pld6 = _sub(plb6, pla6, P)
        pld7 = _sub(plb7, pla7, P)
        plm0, plm1, plm2, plm3, plm4, plm5, plm6, plm7 = _emul(pld0, pld1, pld2, pld3, pld4, pld5, pld6, pld7, rr0, rr1, rr2, rr3, rr4, rr5, rr6, rr7, P, MU, B11)
        plo0 = _add(pla0, plm0, P)
        plo1 = _add(pla1, plm1, P)
        plo2 = _add(pla2, plm2, P)
        plo3 = _add(pla3, plm3, P)
        plo4 = _add(pla4, plm4, P)
        plo5 = _add(pla5, plm5, P)
        plo6 = _add(pla6, plm6, P)
        plo7 = _add(pla7, plm7, P)
        tl.store(plo + 0 * s_out + y, plo0.to(tl.int32, bitcast=True), mask=mask)
        tl.store(plo + 1 * s_out + y, plo1.to(tl.int32, bitcast=True), mask=mask)
        tl.store(plo + 2 * s_out + y, plo2.to(tl.int32, bitcast=True), mask=mask)
        tl.store(plo + 3 * s_out + y, plo3.to(tl.int32, bitcast=True), mask=mask)
        tl.store(plo + 4 * s_out + y, plo4.to(tl.int32, bitcast=True), mask=mask)
        tl.store(plo + 5 * s_out + y, plo5.to(tl.int32, bitcast=True), mask=mask)
        tl.store(plo + 6 * s_out + y, plo6.to(tl.int32, bitcast=True), mask=mask)
        tl.store(plo + 7 * s_out + y, plo7.to(tl.int32, bitcast=True), mask=mask)
        pra0 = tl.load(pr + 0 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pra1 = tl.load(pr + 1 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pra2 = tl.load(pr + 2 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pra3 = tl.load(pr + 3 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pra4 = tl.load(pr + 4 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pra5 = tl.load(pr + 5 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pra6 = tl.load(pr + 6 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        pra7 = tl.load(pr + 7 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb0 = tl.load(pr + 0 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb1 = tl.load(pr + 1 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb2 = tl.load(pr + 2 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb3 = tl.load(pr + 3 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb4 = tl.load(pr + 4 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb5 = tl.load(pr + 5 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb6 = tl.load(pr + 6 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prb7 = tl.load(pr + 7 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        prd0 = _sub(prb0, pra0, P)
        prd1 = _sub(prb1, pra1, P)
        prd2 = _sub(prb2, pra2, P)
        prd3 = _sub(prb3, pra3, P)
        prd4 = _sub(prb4, pra4, P)
        prd5 = _sub(prb5, pra5, P)
        prd6 = _sub(prb6, pra6, P)
        prd7 = _sub(prb7, pra7, P)
        prm0, prm1, prm2, prm3, prm4, prm5, prm6, prm7 = _emul(prd0, prd1, prd2, prd3, prd4, prd5, prd6, prd7, rr0, rr1, rr2, rr3, rr4, rr5, rr6, rr7, P, MU, B11)
        pro0 = _add(pra0, prm0, P)
        pro1 = _add(pra1, prm1, P)
        pro2 = _add(pra2, prm2, P)
        pro3 = _add(pra3, prm3, P)
        pro4 = _add(pra4, prm4, P)
        pro5 = _add(pra5, prm5, P)
        pro6 = _add(pra6, prm6, P)
        pro7 = _add(pra7, prm7, P)
        tl.store(pro + 0 * s_out + y, pro0.to(tl.int32, bitcast=True), mask=mask)
        tl.store(pro + 1 * s_out + y, pro1.to(tl.int32, bitcast=True), mask=mask)
        tl.store(pro + 2 * s_out + y, pro2.to(tl.int32, bitcast=True), mask=mask)
        tl.store(pro + 3 * s_out + y, pro3.to(tl.int32, bitcast=True), mask=mask)
        tl.store(pro + 4 * s_out + y, pro4.to(tl.int32, bitcast=True), mask=mask)
        tl.store(pro + 5 * s_out + y, pro5.to(tl.int32, bitcast=True), mask=mask)
        tl.store(pro + 6 * s_out + y, pro6.to(tl.int32, bitcast=True), mask=mask)
        tl.store(pro + 7 * s_out + y, pro7.to(tl.int32, bitcast=True), mask=mask)
        qla0 = tl.load(ql + 0 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qla1 = tl.load(ql + 1 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qla2 = tl.load(ql + 2 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qla3 = tl.load(ql + 3 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qla4 = tl.load(ql + 4 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qla5 = tl.load(ql + 5 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qla6 = tl.load(ql + 6 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qla7 = tl.load(ql + 7 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb0 = tl.load(ql + 0 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb1 = tl.load(ql + 1 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb2 = tl.load(ql + 2 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb3 = tl.load(ql + 3 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb4 = tl.load(ql + 4 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb5 = tl.load(ql + 5 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb6 = tl.load(ql + 6 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qlb7 = tl.load(ql + 7 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qld0 = _sub(qlb0, qla0, P)
        qld1 = _sub(qlb1, qla1, P)
        qld2 = _sub(qlb2, qla2, P)
        qld3 = _sub(qlb3, qla3, P)
        qld4 = _sub(qlb4, qla4, P)
        qld5 = _sub(qlb5, qla5, P)
        qld6 = _sub(qlb6, qla6, P)
        qld7 = _sub(qlb7, qla7, P)
        qlm0, qlm1, qlm2, qlm3, qlm4, qlm5, qlm6, qlm7 = _emul(qld0, qld1, qld2, qld3, qld4, qld5, qld6, qld7, rr0, rr1, rr2, rr3, rr4, rr5, rr6, rr7, P, MU, B11)
        qlo0 = _add(qla0, qlm0, P)
        qlo1 = _add(qla1, qlm1, P)
        qlo2 = _add(qla2, qlm2, P)
        qlo3 = _add(qla3, qlm3, P)
        qlo4 = _add(qla4, qlm4, P)
        qlo5 = _add(qla5, qlm5, P)
        qlo6 = _add(qla6, qlm6, P)
        qlo7 = _add(qla7, qlm7, P)
        tl.store(qlo + 0 * s_out + y, qlo0.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qlo + 1 * s_out + y, qlo1.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qlo + 2 * s_out + y, qlo2.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qlo + 3 * s_out + y, qlo3.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qlo + 4 * s_out + y, qlo4.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qlo + 5 * s_out + y, qlo5.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qlo + 6 * s_out + y, qlo6.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qlo + 7 * s_out + y, qlo7.to(tl.int32, bitcast=True), mask=mask)
        qra0 = tl.load(qr + 0 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qra1 = tl.load(qr + 1 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qra2 = tl.load(qr + 2 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qra3 = tl.load(qr + 3 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qra4 = tl.load(qr + 4 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qra5 = tl.load(qr + 5 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qra6 = tl.load(qr + 6 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qra7 = tl.load(qr + 7 * s_in + 2 * y, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb0 = tl.load(qr + 0 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb1 = tl.load(qr + 1 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb2 = tl.load(qr + 2 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb3 = tl.load(qr + 3 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb4 = tl.load(qr + 4 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb5 = tl.load(qr + 5 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb6 = tl.load(qr + 6 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrb7 = tl.load(qr + 7 * s_in + 2 * y + 1, mask=mask, other=0).to(tl.uint32, bitcast=True)
        qrd0 = _sub(qrb0, qra0, P)
        qrd1 = _sub(qrb1, qra1, P)
        qrd2 = _sub(qrb2, qra2, P)
        qrd3 = _sub(qrb3, qra3, P)
        qrd4 = _sub(qrb4, qra4, P)
        qrd5 = _sub(qrb5, qra5, P)
        qrd6 = _sub(qrb6, qra6, P)
        qrd7 = _sub(qrb7, qra7, P)
        qrm0, qrm1, qrm2, qrm3, qrm4, qrm5, qrm6, qrm7 = _emul(qrd0, qrd1, qrd2, qrd3, qrd4, qrd5, qrd6, qrd7, rr0, rr1, rr2, rr3, rr4, rr5, rr6, rr7, P, MU, B11)
        qro0 = _add(qra0, qrm0, P)
        qro1 = _add(qra1, qrm1, P)
        qro2 = _add(qra2, qrm2, P)
        qro3 = _add(qra3, qrm3, P)
        qro4 = _add(qra4, qrm4, P)
        qro5 = _add(qra5, qrm5, P)
        qro6 = _add(qra6, qrm6, P)
        qro7 = _add(qra7, qrm7, P)
        tl.store(qro + 0 * s_out + y, qro0.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qro + 1 * s_out + y, qro1.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qro + 2 * s_out + y, qro2.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qro + 3 * s_out + y, qro3.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qro + 4 * s_out + y, qro4.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qro + 5 * s_out + y, qro5.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qro + 6 * s_out + y, qro6.to(tl.int32, bitcast=True), mask=mask)
        tl.store(qro + 7 * s_out + y, qro7.to(tl.int32, bitcast=True), mask=mask)


_PROFILE = os.environ.get("PVI_GKR_PROFILE") == "1"
PROFILE: dict[str, float] = {}
"""With ``PVI_GKR_PROFILE=1``: seconds per phase of the last proofs (each phase synchronised; for measurements)."""
_LAST = [0.0]


def _tick(name: str, dev) -> None:
    if not _PROFILE:
        return
    import time
    torch.cuda.synchronize(dev)
    now = time.perf_counter()
    if name != "start":
        PROFILE[name] = PROFILE.get(name, 0.0) + now - _LAST[0]
    _LAST[0] = now


def _grid(n: int):
    return (max(1, triton.cdiv(n, BLOCK)),)


def _planes_mont(a: torch.Tensor, device) -> torch.Tensor:
    """Canonical AoS ``[n, 8]`` int64 -> Montgomery SoA ``[8, n]`` int32 on ``device`` (tests and small inputs)."""
    m = (a.to(torch.int64) % PRIME) * R_MOD % PRIME
    return m.T.contiguous().to(torch.int32).to(device)


def _combine(p: torch.Tensor, q: torch.Tensor):
    m = p.shape[1] // 2
    po = torch.empty(8, m, dtype=torch.int32, device=p.device)
    qo = torch.empty_like(po)
    _combine_kernel[_grid(m)](p, q, po, qo, m, p.shape[1], m, **_consts(), BLOCK=BLOCK)
    return po, qo


def _eq_step(t: torch.Tensor, r: list[int], inter: int) -> torch.Tensor:
    """``t`` ``[8, m]`` times ``(1 - r, r)`` for a new variable: appended as the high bit (``inter = 0``: entries
    ``y`` and ``y + m``) or prepended as the low bit (``inter = 1``: entries ``2y`` and ``2y + 1``)."""
    m = t.shape[1]
    s = [(R_MOD - r[0]) % PRIME] + [(PRIME - c) % PRIME for c in r[1:]]
    out = torch.empty(8, 2 * m, dtype=torch.int32, device=t.device)
    _eq_kernel[_grid(m)](t, out, *r, *s, m, m, 2 * m, inter, **_consts(), BLOCK=BLOCK)
    return out


def _one(device) -> torch.Tensor:
    t = torch.zeros(8, 1, dtype=torch.int32, device=device)
    t[0, 0] = R_MOD
    return t


def _eq_table(rho_mont: list[list[int]], device) -> torch.Tensor:
    """``eq(rho, bits(y))`` ``[8, 2^k]``, bit ``i`` of ``y`` against ``rho[i]`` (as ``extfield.eq_table``)."""
    t = _one(device)
    for r in rho_mont:
        t = _eq_step(t, r, 0)
    return t


def _suffix_tables(rho_mont: list[list[int]], device) -> list[torch.Tensor]:
    """``[eq_table(rho[j+1:]) for j < k]``, built from the last one by prepending one low bit at a time."""
    k = len(rho_mont)
    out = [None] * k
    t = _one(device)
    out[k - 1] = t
    for j in range(k - 2, -1, -1):
        t = _eq_step(t, rho_mont[j + 1], 1)
        out[j] = t
    return out


# -- single elements of F on the host, as lists of 8 Python ints (much cheaper than 8-entry tensors per round)
def _fm(a, b):
    c = [0] * 15
    for i, ai in enumerate(a):
        if ai:
            for j, bj in enumerate(b):
                c[i + j] += ai * bj
    return [(c[k] + 11 * c[k + 8]) % PRIME for k in range(7)] + [c[7] % PRIME]


def _fa(a, b):
    return [(x + y) % PRIME for x, y in zip(a, b)]


def _fs(a, b):
    return [(x - y) % PRIME for x, y in zip(a, b)]


def _fk(a, k: int):
    return [x * k % PRIME for x in a]


def _fc(c: int):
    return [c % PRIME] + [0] * 7


def _li(t: torch.Tensor):
    return [int(v) for v in t.tolist()]


def _absorb(ch, label: str, v: torch.Tensor) -> None:
    ch.absorb(label.encode(), v.reshape(-1).to(torch.int64).contiguous().cpu().numpy().tobytes())


def _prove_tree(layers: list, ch, label: str):
    """The transcript from the tree's layers (``layers[k]``: Montgomery SoA ``(p, q)`` of ``2^k`` nodes)."""
    from .logup_gkr import Transcript

    n = len(layers) - 1
    p1, q1 = layers[1]
    _tick("start", p1.device)
    top = _from_mont(torch.stack([p1[:, 0], p1[:, 1], q1[:, 0], q1[:, 1]]).cpu())
    tr = Transcript(n, top)
    _absorb(ch, label + "top", top)
    rho = [ch.ext(label + "mu0")[0]]
    dev = p1.device
    one = _fc(1)
    for k in range(1, n):
        lam = ch.ext(label + f"lam{k}")[0]
        cp, cq = layers[k + 1]
        arrs = [cp[:, 0::2].contiguous(), cp[:, 1::2].contiguous(), cq[:, 0::2].contiguous(), cq[:, 1::2].contiguous()]
        layers[k + 1] = None                     # its halves are all this layer reads
        _tick("halves", dev)
        lam_m = _to_mont(lam)
        scale = one                              # prod_{i<j} eq(rho_i, r_i)
        suffixes = _suffix_tables([_to_mont(r) for r in rho], dev)
        _tick("suffix", dev)
        rounds, rs = [], []
        for j in range(k):
            # g_j(t) = scale eq(rho_j, t) h(t), h(t) = sum_y eq(rho_{>j}, y) F(t, y) of degree 2: the kernel gives
            # h(0), h(1), h(2); the transcript is the eager prover's g(0), g(2), g(3)
            m = arrs[0].shape[1]
            half = m // 2
            nb = _grid(half)[0]
            suffix, suffixes[j] = suffixes[j], None
            part = torch.empty(nb, 3, 8, dtype=torch.int64, device=dev)
            _round2_kernel[(nb,)](suffix, *arrs, part, *lam_m, half, m, **_consts(), BLOCK=BLOCK)
            del suffix
            _tick("round", dev)
            h0, h1, h2 = (_li(v) for v in _from_mont(part.sum(0).cpu() % PRIME))
            rj = _li(rho[j])
            e0 = _fs(one, rj)
            e2, e3 = _fs(_fk(rj, 3), one), _fs(_fk(rj, 5), _fc(2))
            g0 = _fm(scale, _fm(e0, h0))
            h3 = _fa(_fs(h0, _fk(h1, 3)), _fk(h2, 3))
            g2, g3 = _fm(scale, _fm(e2, h2)), _fm(scale, _fm(e3, h3))
            g = torch.tensor([g0, g2, g3], dtype=torch.int64)
            _absorb(ch, label + f"g{k}.{j}", g)
            rounds.append(g)
            r = ch.ext(label + f"r{k}.{j}")[0]
            rs.append(r)
            rl = _li(r)
            scale = _fm(scale, _fa(_fm(rj, rl), _fm(_fs(one, rj), _fs(one, rl))))
            _tick("host", dev)
            outs = [torch.empty(8, half, dtype=torch.int32, device=dev) for _ in range(4)]
            _fold4_kernel[_grid(half)](*arrs, *outs, *_to_mont(r), half, m, half, **_consts(), BLOCK=BLOCK)
            arrs = outs
            _tick("fold", dev)
        vals = _from_mont(torch.stack([a[:, 0] for a in arrs]).cpu())
        _absorb(ch, label + f"v{k}", vals)
        tr.rounds.append(torch.stack(rounds))
        tr.vals.append(vals)
        rho = [ch.ext(label + f"mu{k}")[0]] + rs
    tr.point = torch.stack(rho)
    return tr


def _tree(p: torch.Tensor, q: torch.Tensor) -> list:
    _tick("start", p.device)
    layers = [(p, q)]
    while layers[-1][0].shape[1] > 1:
        layers.append(_combine(*layers[-1]))
    _tick("tree", p.device)
    return layers[::-1]


def prove(p: torch.Tensor, q: torch.Tensor, ch, label: str, device="cuda"):
    """:func:`logup_gkr.prove` on the GPU for canonical leaves ``p, q`` ``[2^n, 8]`` (int64, any device)."""
    return _prove_tree(_tree(_planes_mont(p, device), _planes_mont(q, device)), ch, label)


def prove_leaves(delta: torch.Tensor, width: torch.Tensor, n_col: int, n: int, alpha: torch.Tensor, ch, label: str,
                 device="cuda"):
    """The transcript of the instance whose real entries are ``delta``, ``width`` ``[R, T]`` (integers, as
    :func:`logup.leaves` lays them out), its leaves built on the device."""
    rows, cols = delta.shape
    total = 1 << n
    # uploaded as they are (the prover's witness is int32), reduced into the field on the device
    d = torch.remainder(delta.to(device, non_blocking=True).to(torch.int64), PRIME).to(torch.int32).contiguous()
    w = torch.remainder(width.to(device, non_blocking=True).to(torch.int64), PRIME).to(torch.int32).contiguous()
    p = torch.empty(8, total, dtype=torch.int32, device=device)
    q = torch.empty_like(p)
    _leaf_kernel[_grid(total)](d, w, p, q, *_to_mont(alpha), rows, cols, n_col, total, total, PRIME, MU, R2, R_MOD,
                               BLOCK=BLOCK)
    del d, w
    return _prove_tree(_tree(p, q), ch, label)
